Optimalizuj Dockerfile

diff --git a/php5.4/Dockerfile b/php5.4/Dockerfile
--- a/php5.4/Dockerfile
+++ b/php5.4/Dockerfile
@@ -1,32 +1,57 @@
 FROM debian:wheezy
 
-# apt-get dependencies
-RUN apt-get update
-RUN apt-get install -y git wget curl zip openssh-client
+RUN apt-get update && apt-get install -y wget ca-certificates
 
 # apt-get set sources for PHP (wheezy = php5.4)
-RUN echo "deb http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list
-RUN echo "deb-src http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list
-RUN wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
-
 # apt-get set seource for MONO
-RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
-RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
+RUN echo "deb http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list \
+ && echo "deb-src http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list \
+ && wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg \
+ && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
+ && echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
 
-# Actualize source list
-RUN apt-get update
+# apt-get dependencies
+RUN apt-get update \
+ && apt-get install -y \
+      apache2 \
+      curl \
+      git \
+      mysql-client \
+      mono-complete \
+      mono-devel \
+      mono-reference-assemblies-* \
+      mono-runtime \
+      mono-xbuild \
+      monodevelop-nunit \
+      openssh-client \
+      python \
+      zip
 
-# Install mysql client
-RUN apt-get install -y mysql-client
+RUN a2enmod rewrite
+
+COPY etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
 
 # apt-get install php
-RUN apt-get install -y php5 php5-mysql php5-xdebug php5-json php5-cgi php5-xsl php5-cli php5-fpm php5-imagick php5-readline php5-sqlite php5-common php5-gd php5-curl php5-redis php5-zip
-
-RUN apt-get install -y mariadb-client
-RUN apt-get install -y apache2 libapache2-mod-php5
-
-# apt-get install python
-RUN apt-get install -y python
+RUN apt-get install -y \
+      libapache2-mod-php5 \
+      php5 \
+      php5-cgi \
+      php5-cli \
+      php5-common \
+      php5-curl \
+      php5-fpm \
+      php5-gd \
+      php5-imagick \
+      php5-json \
+      php5-mysql \
+      php5-readline \
+      php5-redis \
+      php5-sqlite \
+      php5-xdebug \
+      php5-xsl
 
 # disabled xdebug
 RUN sed -i "s/^/;/g" /etc/php5/cli/conf.d/20-xdebug.ini
@@ -36,9 +61,3 @@ RUN php -r "if(version_compare(PHP_VERSION, '5.4.0', '<') || version_compare(PHP
 
 # Composer
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
-
-# Install Mono + nUnit
-RUN apt-get install -y mono-complete mono-devel monodevelop-nunit mono-reference-assemblies-*
-
-# test Mono version
-RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
diff --git a/php5.6/Dockerfile b/php5.6/Dockerfile
--- a/php5.6/Dockerfile
+++ b/php5.6/Dockerfile
@@ -1,28 +1,54 @@
 FROM ubuntu:xenial
 
-# apt-get dependencies
-RUN apt-get update
-RUN apt-get install -y git wget curl zip openssh-client
-
 # apt-get set sources for PHP 5.6
-RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
-RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
-RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
+RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list \
+ && echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
 
-# Actualize source list
-RUN apt-get update
+# apt-get dependencies
+RUN apt-get update \
+ && apt-get install -y \
+      apache2 \
+      curl \
+      git \
+      mariadb-client \
+      mono-complete \
+      mono-devel \
+      mono-reference-assemblies-* \
+      mono-runtime \
+      mono-xbuild \
+      monodevelop-nunit \
+      openssh-client \
+      python \
+      wget \
+      zip
 
-# Install mysql client
-RUN apt-get install -y mysql-client
+RUN a2enmod rewrite
+
+COPY etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
 
 # apt-get install php
-RUN apt-get install -y php5.6 php5.6-mysql php5.6-xdebug php5.6-json php5.6-cgi php5.6-xsl php5.6-cli php5.6-fpm php5.6-imagick php5.6-readline php5.6-sqlite php5.6-common php5.6-gd php5.6-curl php5.6-redis php5.6-zip
-
-RUN apt-get install -y mariadb-client
-RUN apt-get install -y apache2 libapache2-mod-php5.6
-
-# apt-get install python
-RUN apt-get install -y python
+RUN apt-get install -y \
+      libapache2-mod-php5.6 \
+      php5.6 \
+      php5.6-cgi \
+      php5.6-cli \
+      php5.6-common \
+      php5.6-curl \
+      php5.6-fpm \
+      php5.6-gd \
+      php5.6-imagick \
+      php5.6-json \
+      php5.6-mysql \
+      php5.6-readline \
+      php5.6-redis \
+      php5.6-sqlite \
+      php5.6-xdebug \
+      php5.6-xsl \
+      php5.6-zip
 
 # disabled xdebug
 RUN sed -i "s/^/;/g" /etc/php/5.6/cli/conf.d/20-xdebug.ini
@@ -32,9 +58,3 @@ RUN php -r "if(version_compare(PHP_VERSION, '5.6.0', '<') || version_compare(PHP
 
 # Composer
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
-
-# Install Mono + nUnit
-RUN apt-get install -y mono-complete mono-devel monodevelop-nunit mono-reference-assemblies-*
-
-# test Mono version
-RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
diff --git a/php7.1/Dockerfile b/php7.1/Dockerfile
--- a/php7.1/Dockerfile
+++ b/php7.1/Dockerfile
@@ -1,43 +1,60 @@
 FROM ubuntu:xenial
 
-# apt-get dependencies
-RUN apt-get update
-RUN apt-get install -y git wget curl zip openssh-client
-
 # apt-get set sources for PHP 7.1
-RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
-RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
-RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
+RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list \
+ && echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
 
-# Actualize source list
-RUN apt-get update
+# apt-get dependencies
+RUN apt-get update \
+ && apt-get install -y \
+      apache2 \
+      curl \
+      git \
+      mariadb-client \
+      mono-complete \
+      mono-devel \
+      mono-reference-assemblies-* \
+      mono-runtime \
+      mono-xbuild \
+      monodevelop-nunit \
+      openssh-client \
+      python \
+      wget \
+      zip
 
-# Install mysql client
-RUN apt-get install -y mysql-client
+RUN a2enmod rewrite
+
+COPY etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
 
 # apt-get install php
-RUN apt-get install -y php7.1 php7.1-mysql php7.1-json php7.1-cgi php7.1-xsl php7.1-cli php7.1-fpm php7.1-readline php7.1-sqlite php7.1-common php7.1-gd php7.1-curl php7.1-zip
-
-RUN apt-get install -y mariadb-client
-RUN apt-get install -y apache2 libapache2-mod-php7.1
-
-# apt-get install python
-RUN apt-get install -y python
-
-# @todo add missing packages
-# RUN apt-get install -y php7.1-redis php7.1-xdebug php7.1-imagick
+RUN apt-get install -y \
+      libapache2-mod-php7.1 \
+      php7.1 \
+      php7.1-cgi \
+      php7.1-cli \
+      php7.1-common \
+      php7.1-curl \
+      php7.1-fpm \
+      php7.1-gd \
+      # php7.1-imagick \
+      php7.1-json \
+      php7.1-mysql \
+      php7.1-readline \
+      # php7.1-redis \
+      php7.1-sqlite \
+      # php7.1-xdebug \
+      php7.1-xsl \
+      php7.1-zip
 
 # disabled xdebug
-#RUN sed -i "s/^/;/g" /etc/php/7.1/cli/conf.d/20-xdebug.ini
+# RUN sed -i "s/^/;/g" /etc/php/7.1/cli/conf.d/20-xdebug.ini
 
 # test PHP version
 RUN php -r "if(strpos(PHP_VERSION, '7.1.') !== 0){ echo 'Invalid PHP version '.PHP_VERSION; exit(1); }"
 
 # Composer
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
-
-# Install Mono + nUnit
-RUN apt-get install -y mono-complete mono-devel monodevelop-nunit mono-reference-assemblies-*
-
-# test Mono version
-RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
