php 5.5-7.1 use ubuntu xenial php 5.4 use debian wheezy add mono version 4 + test

diff --git a/php5.4/Dockerfile b/php5.4/Dockerfile
--- a/php5.4/Dockerfile
+++ b/php5.4/Dockerfile
@@ -8,6 +8,12 @@ RUN apt-get install -y git wget curl zip
 RUN echo "deb http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list
 RUN echo "deb-src http://packages.dotdeb.org wheezy all" >> /etc/apt/sources.list
 RUN wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
+
+# apt-get set seource for MONO
+RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
+RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
+
+# Actualize source list
 RUN apt-get update
 
 # apt-get install php
@@ -27,3 +33,6 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
 
 # Install Mono + nUnit
 RUN apt-get install -y mono-complete mono-devel monodevelop-nunit
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
diff --git a/php5.5/Dockerfile b/php5.5/Dockerfile
--- a/php5.5/Dockerfile
+++ b/php5.5/Dockerfile
@@ -1,23 +1,25 @@
-FROM debian:wheezy
+FROM ubuntu:xenial
 
 # apt-get dependencies
 RUN apt-get update
 RUN apt-get install -y git wget curl zip
 
-# apt-get set sources for PHP (wheezy-php5.5 = php5.5)
-RUN echo "deb http://packages.dotdeb.org wheezy-php55 all" >> /etc/apt/sources.list
-RUN echo "deb-src http://packages.dotdeb.org wheezy-php55 all" >> /etc/apt/sources.list
-RUN wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
+# apt-get set sources for PHP 5.5
+RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
+RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
+RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
+
+# Actualize source list
 RUN apt-get update
 
 # apt-get install php
-RUN apt-get install -y php5 php5-mysql php5-xdebug php5-json php5-cgi php5-xsl php5-cli php5-fpm php5-imagick php5-readline php5-sqlite php5-common php5-gd php5-curl php5-redis
+RUN apt-get install -y php5.5 php5.5-mysql php5.5-xdebug php5.5-json php5.5-cgi php5.5-xsl php5.5-cli php5.5-fpm php5.5-imagick php5.5-readline php5.5-sqlite php5.5-common php5.5-gd php5.5-curl php5.5-redis
 
 # apt-get install python
 RUN apt-get install -y python
 
 # disabled xdebug
-RUN sed -i "s/^/;/g" /etc/php5/cli/conf.d/20-xdebug.ini
+RUN sed -i "s/^/;/g" /etc/php/5.5/cli/conf.d/20-xdebug.ini
 
 # test PHP version
 RUN php -r "if(version_compare(PHP_VERSION, '5.5.0', '<') || version_compare(PHP_VERSION, '5.6.0', '>=')){ echo 'Invalid PHP version '.PHP_VERSION; exit(1); }"
@@ -27,3 +29,6 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
 
 # Install Mono + nUnit
 RUN apt-get install -y mono-complete mono-devel monodevelop-nunit
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
diff --git a/php5.6/Dockerfile b/php5.6/Dockerfile
--- a/php5.6/Dockerfile
+++ b/php5.6/Dockerfile
@@ -1,23 +1,25 @@
-FROM debian:wheezy
+FROM ubuntu:xenial
 
 # apt-get dependencies
 RUN apt-get update
 RUN apt-get install -y git wget curl zip
 
-# apt-get set sources for PHP (wheezy-php5.6 = php5.6)
-RUN echo "deb http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list
-RUN echo "deb-src http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list
-RUN wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
+# apt-get set sources for PHP 5.6
+RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
+RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
+RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
+
+# Actualize source list
 RUN apt-get update
 
 # apt-get install php
-RUN apt-get install -y php5 php5-mysql php5-xdebug php5-json php5-cgi php5-xsl php5-cli php5-fpm php5-imagick php5-readline php5-sqlite php5-common php5-gd php5-curl php5-redis
+RUN apt-get install -y php5.6 php5.6-mysql php5.6-xdebug php5.6-json php5.6-cgi php5.6-xsl php5.6-cli php5.6-fpm php5.6-imagick php5.6-readline php5.6-sqlite php5.6-common php5.6-gd php5.6-curl php5.6-redis
 
 # apt-get install python
 RUN apt-get install -y python
 
 # disabled xdebug
-RUN sed -i "s/^/;/g" /etc/php5/cli/conf.d/20-xdebug.ini
+RUN sed -i "s/^/;/g" /etc/php/5.6/cli/conf.d/20-xdebug.ini
 
 # test PHP version
 RUN php -r "if(version_compare(PHP_VERSION, '5.6.0', '<') || version_compare(PHP_VERSION, '5.7.0', '>=')){ echo 'Invalid PHP version '.PHP_VERSION; exit(1); }"
@@ -27,3 +29,6 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
 
 # Install Mono + nUnit
 RUN apt-get install -y mono-complete mono-devel monodevelop-nunit
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
diff --git a/php7.1/Dockerfile b/php7.1/Dockerfile
--- a/php7.1/Dockerfile
+++ b/php7.1/Dockerfile
@@ -8,6 +8,8 @@ RUN apt-get install -y git wget curl zip
 RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
 RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" >> /etc/apt/sources.list
 RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
+
+# Actualize source list
 RUN apt-get update
 
 # apt-get install php
@@ -30,3 +32,6 @@ RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local
 
 # Install Mono + nUnit
 RUN apt-get install -y mono-complete mono-devel monodevelop-nunit
+
+# test Mono version
+RUN (mono -V | grep "version 4.") || (echo "Missing mono version 4" && mono -V && exit 1)
